export const nigerianBanks = [
    { name: "Abbey Mortgage Bank", code: "801" },
    { name: "Above Only MFB", code: "51221" },
    { name: "Access Bank", code: "044" },
    { name: "Access Bank (Diamond)", code: "063" },
    { name: "ALAT by WEMA", code: "035A" },
    { name: "Amju Unique MFB", code: "50926" },
    { name: "ASO Savings and Loans", code: "401" },
    { name: "Baines Credit MFB", code: "51229" },
    { name: "Bowen Microfinance Bank", code: "50931" },
    { name: "Carbon", code: "565" },
    { name: "CEMCS Microfinance Bank", code: "50161" },
    { name: "Citibank Nigeria", code: "023" },
    { name: "Ecobank Nigeria", code: "050" },
    { name: "Ekondo Microfinance Bank", code: "562" },
    { name: "Eyowo", code: "50126" },
    { name: "Fidelity Bank", code: "070" },
    { name: "Firmus MFB", code: "51314" },
    { name: "First Bank of Nigeria", code: "011" },
    { name: "First City Monument Bank", code: "214" },
    { name: "FSDH Merchant Bank", code: "501" },
    { name: "Globus Bank", code: "103" },
    { name: "GoMoney", code: "100022" },
    { name: "Guaranty Trust Bank", code: "058" },
    { name: "Hackman Microfinance Bank", code: "51251" },
    { name: "Hasal Microfinance Bank", code: "50383" },
    { name: "Heritage Bank", code: "030" },
    { name: "Hope PSBank", code: "120002" },
    { name: "Ibile Microfinance Bank", code: "51244" },
    { name: "Jaiz Bank", code: "301" },
    { name: "Keystone Bank", code: "082" },
    { name: "Kuda Bank", code: "50211" },
    { name: "Lagos Building Investment Company Plc.", code: "90052" },
    { name: "Lotus Bank", code: "303" },
    { name: "Mayfair MFB", code: "50563" },
    { name: "Mint MFB", code: "50304" },
    { name: "Moniepoint MFB", code: "50515" },
    { name: "Mutual Trust Microfinance Bank", code: "50573" },
    { name: "Opay", code: "999992" },
    { name: "Paga", code: "100002" },
    { name: "Palmpay", code: "999991" },
    { name: "Parallex Bank", code: "526" },
    { name: "Paystack", code: "999999" }, // Generic code often used for payment gateways
    { name: "Peace Microfinance Bank", code: "50743" },
    { name: "Polaris Bank", code: "076" },
    { name: "PremiumTrust Bank", code: "105" },
    { name: "Providus Bank", code: "101" },
    { name: "Rand Merchant Bank", code: "502" },
    { name: "Refuge Mortgage Bank", code: "90067" },
    { name: "Rubies Microfinance Bank", code: "125" },
    { name: "Sparkle Microfinance Bank", code: "51310" },
    { name: "Stanbic IBTC Bank", code: "221" },
    { name: "Standard Chartered Bank", code: "068" },
    { name: "Sterling Bank", code: "232" },
    { name: "Suntrust Bank", code: "100" },
    { name: "TAJ Bank", code: "302" },
    { name: "TCF MFB", code: "51211" },
    { name: "Titan Trust Bank", code: "102" },
    { name: "Union Bank of Nigeria", code: "032" },
    { name: "United Bank for Africa", code: "033" },
    { name: "Unity Bank", code: "215" },
    { name: "VFD Microfinance Bank", code: "566" },
    { name: "Wema Bank", code: "035" },
    { name: "Zenith Bank", code: "057" },
];
